### ISSUE TITLE
cant compile on fedora 12 with gcc 4.4.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [harshjv/cvblob#8]
```
I tried to compile cvBlob and it gave me error

In function ‘void cvb::cvWriteContourPolygonSVG(const
cvb::CvContourPolygon&, const std::string&, const CvScalar&, const 
CvScalar&)’:
/Development/cvblob/cvBlob/cvcontour.cpp:417: error: variable
‘std::stringstream buffer’ has initializer but incomplete type
make[2]: *** [lib/CMakeFiles/cvblob.dir/cvcontour.o] Error 1
make[1]: *** [lib/CMakeFiles/cvblob.dir/all] Error 2
make: *** [all] Error 2

I added '# include <sstream>' in file cvcontour.cpp located in cvBlob
directory and it just compiled well.

Just wanted to let you know of the error and the solution.

Thanks.

```

Original issue reported on code.google.com by `amitpate...@gmail.com` on 25 Feb 2010 at 1:08

**Comment by GoogleCodeExporter** [comment]
```
Thank you very much!

I've added the line to the repository.

Best regards,

Cristóbal
```

Original comment by `grendel....@gmail.com` on 25 Feb 2010 at 10:19
- Changed state: **Verified**
